on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ftp-ptitrest.alwaysdata.net
          username: ptitrest
          password: ${{ secrets.ftp_password }}
          source: "./"  # Dossier de fichiers source
          target: "/www/"  # Dossier cible sur le serveur
          port: 22  # Port par défaut pour SFTP

