name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy via FTP
      uses: appleboy/ftp-action@v0.2.0
      with:
        host: ftp-ptitrest.alwaysdata.net
        username: ptitrest
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        localDir: ./  # Dossier source (racine du projet sur GitHub Actions)
        remoteDir: /www/  # Dossier cible sur le serveur

