on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp-ptitrest.alwaysdata.net
        username: ptitrest
        password: ${{ secrets.ftp_password }}
        server-dir: /www/
       exclude: |
        **/.git*
        **/.git*/**
        **/node_modules/Bootstrap/scss/**
        **/node_modules/Bootstrap/js/**
        **/node_modules/Bootstrap-icons/icons/**
